(def ^:private x 1)
(def y (if-let [a 1] a 2))
#?(:clj (only-clj 1) :cljs (only-cljs 2))
(def z #?@(:clj [1 2] :cljs [3]))
(def q (quote (a b)))
(def u `(~x ~@y))
(def nm #:ns {:a 1})
(def m #{"a" :b})
(def d @r)
